// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apindien2;

#nullable disable

namespace apindien2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("apindien2.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<int>("Surface")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Villa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 30, 18, 49, 46, 413, DateTimeKind.Local).AddTicks(2531),
                            Name = "Villa 1",
                            Occupancy = 4,
                            Surface = 100,
                            UpdatedAt = new DateTime(2024, 3, 30, 18, 49, 46, 413, DateTimeKind.Local).AddTicks(2659)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 30, 18, 49, 46, 413, DateTimeKind.Local).AddTicks(2663),
                            Name = "Villa 2",
                            Occupancy = 6,
                            Surface = 200,
                            UpdatedAt = new DateTime(2024, 3, 30, 18, 49, 46, 413, DateTimeKind.Local).AddTicks(2664)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
